services:
  - type: web
    name: zk-vault
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: TURSO_DATABASE_URL
        sync: false # Set this in the Render UI
      - key: TURSO_AUTH_TOKEN
        sync: false # Set this in the Render UI
